version: '3.8'

services:
  embedding_model:
    build:
      context: ./embedding_model
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  vector_db:
    build:
      context: ./vector_db
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  framework:
    build:
      context: ./framework
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
