version: '3.8'

services:
  embedding_model:
    build:
      context: ./embedding_model
    ports:
      - "5001:5000"

  vector_db:
    image: qdrant/qdrant:v1.1.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  framework:
    build:
      context: ./framework
    ports:
      - "5000:5000"
    depends_on:
      - embedding_model
      - vector_db

  llm:
    build:
      context: ./llm
    ports:
      - "5002:5000"

volumes:
  qdrant_storage:
