version: '3.8'

services:
  framework:
    build: ./framework
    ports:
      - "5001:5001"
    depends_on:
      - vector_db
      - embedding_model

  embedding_model:
    build: ./embedding_model
    ports:
      - "8000:8000"

  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage  # Qdrant 데이터 디렉토리를 호스트 볼륨에 마운트

volumes:
  qdrant_data:
