version: '3.8'

services:
  embedding_model:
    image: ./embedding_model
    volumes:
      - ./packages:/packages
    ports:
      - "5001:5000"

  vector_db:
    image: qdrant/qdrant:v1.11.3
    volumes:
      - ./packages:/packages
    ports:
      - "6333:6333"

  framework:
    build: ./framework
    volumes:
      - ./packages:/packages
    ports:
      - "5003:5000"

  llm:
    build: ./llm
    volumes:
      - ./packages:/packages
    ports:
      - "5004:5000"


# 

docker build -t yourdockerhubusername/embedding_model:latest ./embedding_model

services:
  embedding_model:
    image: yourdockerhubusername/embedding_model:latest