version: '3.8'

services:
  embedding_model:
    build: ./embedding_model
    ports:
      - "8000:8000"
  
  vector_db:
    build: ./vector_db
    ports:
      - "8001:8001"
    depends_on:
      - embedding_model
    command: ["python", "init_db.py"]
  
  framework:
    build: ./framework
    ports:
      - "8002:8002"
    depends_on:
      - embedding_model
      - vector_db
      - llm
  
  llm:
    build: ./llm
    ports:
      - "8003:8003"
